"""initial appraisal schema

Revision ID: c30c687d34c5
Revises:
Create Date: 2026-10-03 19:30:38.528260

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = "c30c687d34c5"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cycles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("scope", sa.String(length=16), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=True),
        sa.Column("frequency", sa.String(length=16), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column("submission_due", sa.Date(), nullable=False),
        sa.Column("review_due", sa.Date(), nullable=False),
        sa.Column("require_one_to_one", sa.Boolean(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column(
            "launch_summary",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("created_by", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("launched_by", sa.Integer(), nullable=True),
        sa.Column("launched_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("closed_by", sa.Integer(), nullable=True),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "(scope = 'project') = (project_id IS NOT NULL)", name="ck_cycles_project_scope"
        ),
        sa.CheckConstraint(
            "frequency IN ('quarterly', 'half_yearly', 'annual', 'custom')",
            name="ck_cycles_frequency",
        ),
        sa.CheckConstraint("scope IN ('organization', 'project')", name="ck_cycles_scope"),
        sa.CheckConstraint("status IN ('draft', 'active', 'closed')", name="ck_cycles_status"),
        sa.CheckConstraint("end_date >= start_date", name="ck_cycles_dates"),
        sa.CheckConstraint("review_due >= submission_due", name="ck_cycles_due_dates"),
        sa.PrimaryKeyConstraint("id"),
        schema="appraisal",
    )
    op.create_table(
        "notification_outbox",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("event_type", sa.String(length=48), nullable=False),
        sa.Column("recipient_user_id", sa.Integer(), nullable=False),
        sa.Column("cycle_id", sa.Integer(), nullable=True),
        sa.Column("appraisal_id", sa.Integer(), nullable=True),
        sa.Column(
            "payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("dedupe_key", sa.String(length=200), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("dedupe_key"),
        schema="appraisal",
    )
    with op.batch_alter_table("notification_outbox", schema="appraisal") as batch_op:
        batch_op.create_index(
            batch_op.f("ix_appraisal_notification_outbox_status"), ["status"], unique=False
        )

    op.create_table(
        "appraisals",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("cycle_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("employee_name", sa.String(length=300), nullable=False),
        sa.Column("employee_emp_id", sa.String(length=64), nullable=True),
        sa.Column("project_id", sa.Integer(), nullable=True),
        sa.Column("role_type_code", sa.String(length=32), nullable=False),
        sa.Column("form_id", sa.Integer(), nullable=False),
        sa.Column("form_version_id", sa.Integer(), nullable=False),
        sa.Column("form_name", sa.String(length=200), nullable=False),
        sa.Column(
            "form_definition",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("lead_user_id", sa.Integer(), nullable=True),
        sa.Column("lead_name", sa.String(length=300), nullable=True),
        sa.Column("manager_user_id", sa.Integer(), nullable=True),
        sa.Column("manager_name", sa.String(length=300), nullable=True),
        sa.Column("current_reviewer_user_id", sa.Integer(), nullable=True),
        sa.Column("current_review_step_id", sa.Integer(), nullable=True),
        sa.Column("review_attempt", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("needs_reviewer_reason", sa.String(length=300), nullable=True),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("one_to_one_held_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status IN ('not_started', 'draft', 'awaiting_review', 'changes_requested', 'approved', 'needs_reviewer')",
            name="ck_appraisals_status",
        ),
        sa.ForeignKeyConstraint(["cycle_id"], ["appraisal.cycles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("cycle_id", "user_id", name="uq_appraisals_cycle_user"),
        schema="appraisal",
    )
    with op.batch_alter_table("appraisals", schema="appraisal") as batch_op:
        batch_op.create_index(
            batch_op.f("ix_appraisal_appraisals_current_reviewer_user_id"),
            ["current_reviewer_user_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_appraisal_appraisals_lead_user_id"), ["lead_user_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_appraisal_appraisals_manager_user_id"), ["manager_user_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_appraisal_appraisals_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "appraisal_answers",
        sa.Column("appraisal_id", sa.Integer(), nullable=False),
        sa.Column("review_attempt", sa.Integer(), nullable=False),
        sa.Column("review_stage", sa.String(length=16), nullable=False),
        sa.Column("field_key", sa.String(length=64), nullable=False),
        sa.Column(
            "value",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("updated_by", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["appraisal_id"], ["appraisal.appraisals.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("appraisal_id", "review_attempt", "review_stage", "field_key"),
        schema="appraisal",
    )
    op.create_table(
        "appraisal_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("cycle_id", sa.Integer(), nullable=False),
        sa.Column("appraisal_id", sa.Integer(), nullable=True),
        sa.Column("actor_user_id", sa.Integer(), nullable=False),
        sa.Column("action", sa.String(length=48), nullable=False),
        sa.Column("from_status", sa.String(length=32), nullable=True),
        sa.Column("to_status", sa.String(length=32), nullable=True),
        sa.Column(
            "details",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["appraisal_id"], ["appraisal.appraisals.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["cycle_id"], ["appraisal.cycles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        schema="appraisal",
    )
    with op.batch_alter_table("appraisal_events", schema="appraisal") as batch_op:
        batch_op.create_index(
            batch_op.f("ix_appraisal_appraisal_events_appraisal_id"), ["appraisal_id"], unique=False
        )

    op.create_table(
        "appraisal_review_steps",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("appraisal_id", sa.Integer(), nullable=False),
        sa.Column("review_attempt", sa.Integer(), nullable=False),
        sa.Column("sequence_no", sa.Integer(), nullable=False),
        sa.Column("review_stage", sa.String(length=16), nullable=False),
        sa.Column("reviewer_user_id", sa.Integer(), nullable=False),
        sa.Column("reviewer_name", sa.String(length=300), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("activated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["appraisal_id"], ["appraisal.appraisals.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "appraisal_id", "review_attempt", "sequence_no", name="uq_review_steps_order"
        ),
        schema="appraisal",
    )
    with op.batch_alter_table("appraisal_review_steps", schema="appraisal") as batch_op:
        batch_op.create_index(
            "ix_review_steps_reviewer_status", ["reviewer_user_id", "status"], unique=False
        )

    op.create_table(
        "review_comments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("appraisal_id", sa.Integer(), nullable=False),
        sa.Column("review_step_id", sa.Integer(), nullable=True),
        sa.Column("review_attempt", sa.Integer(), nullable=False),
        sa.Column("review_stage", sa.String(length=16), nullable=False),
        sa.Column("author_user_id", sa.Integer(), nullable=False),
        sa.Column("author_name", sa.String(length=300), nullable=True),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["appraisal_id"], ["appraisal.appraisals.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["review_step_id"], ["appraisal.appraisal_review_steps.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="appraisal",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("review_comments", schema="appraisal")
    with op.batch_alter_table("appraisal_review_steps", schema="appraisal") as batch_op:
        batch_op.drop_index("ix_review_steps_reviewer_status")

    op.drop_table("appraisal_review_steps", schema="appraisal")
    with op.batch_alter_table("appraisal_events", schema="appraisal") as batch_op:
        batch_op.drop_index(batch_op.f("ix_appraisal_appraisal_events_appraisal_id"))

    op.drop_table("appraisal_events", schema="appraisal")
    op.drop_table("appraisal_answers", schema="appraisal")
    with op.batch_alter_table("appraisals", schema="appraisal") as batch_op:
        batch_op.drop_index(batch_op.f("ix_appraisal_appraisals_user_id"))
        batch_op.drop_index(batch_op.f("ix_appraisal_appraisals_manager_user_id"))
        batch_op.drop_index(batch_op.f("ix_appraisal_appraisals_lead_user_id"))
        batch_op.drop_index(batch_op.f("ix_appraisal_appraisals_current_reviewer_user_id"))

    op.drop_table("appraisals", schema="appraisal")
    with op.batch_alter_table("notification_outbox", schema="appraisal") as batch_op:
        batch_op.drop_index(batch_op.f("ix_appraisal_notification_outbox_status"))

    op.drop_table("notification_outbox", schema="appraisal")
    op.drop_table("cycles", schema="appraisal")
    # ### end Alembic commands ###
