"""create cohorts, coders, stages, and target-config tables

Revision ID: 2bafdaae6e3b
Revises: 5ca18c7bc58c
Create Date: 2026-09-18 10:50:01.153832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bafdaae6e3b'
down_revision = '5ca18c7bc58c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cohorts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sequence_no', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=False),
    sa.Column('window_start', sa.Date(), nullable=False),
    sa.Column('window_end', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sequence_no')
    )
    op.create_table('stages',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('code'),
    sa.UniqueConstraint('sort_order')
    )
    op.create_table('coders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('join_date', sa.Date(), nullable=False),
    sa.Column('cohort_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cohort_id'], ['cohorts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('full_name')
    )
    op.create_table('coder_aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coder_id', sa.Integer(), nullable=False),
    sa.Column('alias', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['coder_id'], ['coders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alias')
    )
    op.create_table('coder_stage_periods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coder_id', sa.Integer(), nullable=False),
    sa.Column('stage_code', sa.String(length=32), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('shifted_by_exception_days', sa.Integer(), nullable=False),
    sa.CheckConstraint("source IN ('observed_first_activity', 'calendar_offset', 'manual_override')", name='ck_coder_stage_periods_source'),
    sa.ForeignKeyConstraint(['coder_id'], ['coders.id'], ),
    sa.ForeignKeyConstraint(['stage_code'], ['stages.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kairon_completions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coder_id', sa.Integer(), nullable=False),
    sa.Column('mbi', sa.String(length=64), nullable=False),
    sa.Column('level', sa.String(length=32), nullable=False),
    sa.Column('completed_date', sa.Date(), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['coder_id'], ['coders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mbi', 'level', 'coder_id', 'completed_date', name='uq_kairon_completion')
    )
    op.create_table('manual_production_facts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coder_id', sa.Integer(), nullable=False),
    sa.Column('activity_date', sa.Date(), nullable=False),
    sa.Column('production_count', sa.Integer(), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['coder_id'], ['coders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('coder_id', 'activity_date', name='uq_manual_production_fact')
    )
    op.create_table('cohort_join_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coder_id', sa.Integer(), nullable=False),
    sa.Column('candidate_cohort_ids', sa.ARRAY(sa.Integer()), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('resolved_cohort_id', sa.Integer(), nullable=True),
    sa.Column('resolved_by_id', sa.Integer(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'resolved')", name='ck_cohort_join_reviews_status'),
    sa.ForeignKeyConstraint(['coder_id'], ['coders.id'], ),
    sa.ForeignKeyConstraint(['resolved_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['resolved_cohort_id'], ['cohorts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stage_exceptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coder_id', sa.Integer(), nullable=False),
    sa.Column('stage_code', sa.String(length=32), nullable=False),
    sa.Column('extra_days', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['coder_id'], ['coders.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['stage_code'], ['stages.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stage_target_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stage_code', sa.String(length=32), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('daily_target', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('effective_to IS NULL OR effective_to > effective_from', name='ck_stage_target_rules_valid_range'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['stage_code'], ['stages.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    # A plain unique/btree index can't express "no two rows for the same
    # stage_code may have overlapping [effective_from, effective_to) date
    # ranges" - only a GiST exclusion constraint can, and that needs
    # btree_gist for the stage_code equality term (GiST has no native
    # support for text/varchar equality on its own). This is what actually
    # enforces the dev spec's "Non-overlap enforcement" rule at write time,
    # backing up the pre-check in app/cohorts/services.py's
    # overlapping_rule_exists() against a race condition.
    op.execute("CREATE EXTENSION IF NOT EXISTS btree_gist")
    op.execute(
        "ALTER TABLE stage_target_rules ADD CONSTRAINT ex_stage_target_rules_no_overlap "
        "EXCLUDE USING gist (stage_code WITH =, daterange(effective_from, effective_to) WITH &&)"
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stage_target_rules')
    op.drop_table('stage_exceptions')
    op.drop_table('cohort_join_reviews')
    op.drop_table('manual_production_facts')
    op.drop_table('kairon_completions')
    op.drop_table('coder_stage_periods')
    op.drop_table('coder_aliases')
    op.drop_table('coders')
    op.drop_table('stages')
    op.drop_table('cohorts')
    # ### end Alembic commands ###
