"""create projects table

Revision ID: 62812d29913b
Revises: 2315bc38cac3
Create Date: 2026-09-16 19:57:10.143309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62812d29913b'
down_revision = '2315bc38cac3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('projects')
    # ### end Alembic commands ###
