"""create encryption_keys table

Revision ID: e3b43d8e6451
Revises: 363704b36ecb
Create Date: 2026-09-17 07:50:11.459546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3b43d8e6451'
down_revision = '363704b36ecb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('encryption_keys',
    sa.Column('key_version', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('wrapped_key', sa.LargeBinary(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('key_version')
    )
    with op.batch_alter_table('encryption_keys', schema=None) as batch_op:
        batch_op.create_index('ix_encryption_keys_single_active', ['is_active'], unique=True, postgresql_where=sa.text('is_active = true'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('encryption_keys', schema=None) as batch_op:
        batch_op.drop_index('ix_encryption_keys_single_active', postgresql_where=sa.text('is_active = true'))

    op.drop_table('encryption_keys')
    # ### end Alembic commands ###
