"""add microsoft sign-in identities

Autogenerate also reported a pre-existing difference between the office_holidays model and its
migration (unique constraint vs unique index); it is unrelated and left out of this migration.

Revision ID: f1699bb5cd1a
Revises: f057fd6ddc83
Create Date: 2026-10-03 20:26:56.457800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1699bb5cd1a'
down_revision = 'f057fd6ddc83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entra_login_transactions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('flow', sa.JSON(), nullable=False),
    sa.Column('next_path', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('entra_login_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_entra_login_transactions_expires_at'), ['expires_at'], unique=False)

    op.create_table('external_identities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('object_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('link_method', sa.String(length=16), nullable=False),
    sa.Column('linked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_authenticated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'tenant_id', 'object_id', name='uq_external_identities_account')
    )
    with op.batch_alter_table('external_identities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_external_identities_user_id'), ['user_id'], unique=False)
        batch_op.create_index('uq_external_identities_active_user', ['user_id', 'provider'], unique=True, postgresql_where=sa.text("status = 'active'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('external_identities', schema=None) as batch_op:
        batch_op.drop_index('uq_external_identities_active_user', postgresql_where=sa.text("status = 'active'"))
        batch_op.drop_index(batch_op.f('ix_external_identities_user_id'))

    op.drop_table('external_identities')
    with op.batch_alter_table('entra_login_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_entra_login_transactions_expires_at'))

    op.drop_table('entra_login_transactions')
    # ### end Alembic commands ###
